### ISSUE TITLE
support 3.10 3.12 and 3.16

### ISSUE THREAD

**Issue by l300lvl** [sgaraud/gnome-extension-show-ip#1]
I've tested this on 3.10 and 3.16 and have gotten no errors from terminal or looking glass so I'm fairly confident you can add 3.12 and 3.14 as well, so you can easily add those versions to metadata.json instead of me making changes and a pull request. Great extension though!

**Comment by sgaraud** [comment]
Great, thanks for that. I edited the metadata.json. I wanted to test it also but not sure how to get all thoses gnomes versions.
