### ISSUE TITLE
Licensing Confusion

### ISSUE THREAD

**Issue by paddatrapper** [sgaraud/gnome-extension-show-ip#13]
The project seems to be licensed under two different licences. Although they are compatible currently it is confusing.

`extension.js` and `prefs.js` are both licensed under the GPLv2+ (see the file header), however the project is licensed under the GPLv3+ (see `LICENSE`). Furthermore your `README` states the project is GPLv2+. Is this intentional as it makes packaging and distributing tricky?

**Comment by sgaraud** [comment]
thank you for noticing and reporting that problem.
