### ISSUE TITLE
Installation error on latest gnome

### ISSUE THREAD

**Issue by dominikheinz** [sgaraud/gnome-extension-show-ip#22]
Hello,

When I am trying to install _Show-IP_ via _Gnome Shell Integration_ it doesn't install, and just says "Error".
This seems to be happening only with the latest GNOME version.

**Comment by sgaraud** [comment]
I could reproduce the problem with GNOME Shell 3.26.1

**Comment by sgaraud** [comment]
After searching "starting with ECMAScript 2015, TypedArray constructors require to be constructed with a new operator. Calling a TypedArray constructor as a function without new, will throw a TypeError from now on."

This is the issue here.
