### ISSUE TITLE
integrate with main drop down panel like it was in alternative version

### ISSUE THREAD

**Issue by muradm** [sgaraud/gnome-extension-show-ip#24]
In not-more-maintained version of "show IP", it was displayed in drop down panel. 
https://gitlab.com/paddatrapper/show-ip-gnome-extension

that was neat feature. always good to know you IP, but showing it right on top of screen always a security issue. whenever IP address is needed, it is easy to popup main dropdown panel.

also it does not take a space on top bar.

**Comment by sgaraud** [comment]
contribution from paddatrapper is integrated in latest version v8.
go to extension 'Preferences' menu, select 'Show in Dropdown Menu' entry.
